name: solver-tests
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
env:
  BRANCH: 'master'
jobs:
  test:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    env:
      PACKAGE: ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: 'JuMP'
          - package: 'Convex'
          - package: 'SumOfSquares'
          - package: 'PolyJuMP'
          - package: 'Alpine'
          - package: 'Cbc'
          - package: 'Clp'
          - package: 'CDDLib'
          - package: 'COSMO'
          - package: 'CPLEX'
          - package: 'CSDP'
          - package: 'DSDP'
          - package: 'EAGO'
          - package: 'ECOS'
          - package: 'GLPK'
          - package: 'HiGHS'
          - package: 'Hypatia'
          - package: 'Ipopt'
          - package: 'Juniper'
          - package: 'MosekTools'
          - package: 'NLopt'
          - package: 'OSQP'
          - package: 'PATHSolver'
          - package: 'Pavito'
          - package: 'ProxSDP'
          - package: 'SCIP'
          - package: 'SCS'
          - package: 'SDPA'
          - package: 'SDPAFamily'
          - package: 'Tulip'
          - package: 'Xpress'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - uses: julia-actions/julia-buildpkg@v1
      - name: Test
        shell: julia --color=yes {0}
        env:
          CPLEX_VERSION: '2010'
          SECRET_CPLEX_URL_12100: ${{ secrets.SECRET_CPLEX_URL_12100 }}
          SECRET_XPRA_WIN_8130: ${{ secrets.XPRA_WIN_8130 }}
        run: |
          import Pkg
          Pkg.add(Pkg.PackageSpec(; name="MathOptInterface", rev=ENV["BRANCH"]))
          Pkg.develop(ENV["PACKAGE"])
          Pkg.test(ENV["PACKAGE"])
