name: CI
on:
  workflow_dispatch: # allows to trigger it manually
    branches:
      - master
  push:
    branches:
      - master
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    env:
      # To test on a PR, make a PR to update this environment variable.
      BRANCH: 'master'
      PACKAGE: ${{ matrix.package }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: 'JuMP'
          - package: 'Convex'
          - package: 'SumOfSquares'
          - package: 'PolyJuMP'
          - package: 'Alpine'
          - package: 'Cbc'
          - package: 'Clp'
          - package: 'CDDLib'
          - package: 'COSMO'
          - package: 'CSDP'
          - package: 'DSDP'
          - package: 'EAGO' # require gfortran
          - package: 'ECOS'
          - package: 'GLPK'
          - package: 'HiGHS'
          - package: 'Hypatia'
          - package: 'Ipopt'
          - package: 'Juniper'
          - package: 'MosekTools'
          - package: 'NLopt'
          - package: 'OSQP'
          - package: 'PATHSolver'
          - package: 'Pavito'
          - package: 'ProxSDP'
          - package: 'SCIP'
          - package: 'SCS'
          - package: 'SDPA'
          - package: 'SDPAFamily'
          - package: 'Tulip'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Test
        shell: julia --color=yes {0}
        run: |
          import Pkg
          Pkg.add(Pkg.PackageSpec(; name="MathOptInterface", rev=ENV["BRANCH"]))
          Pkg.develop(ENV["PACKAGE"])
          Pkg.test(ENV["PACKAGE"])
  test_xpress:
    name: Xpress
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Test Xpress
        env:
          # To test on a PR, make a PR to update this environment variable.
          BRANCH: 'master'
          SECRET_XPRS_WIN_8110: ${{ secrets.XPRS_WIN_8110 }}
          SECRET_XPRL_WIN_8110: ${{ secrets.XPRL_WIN_8110 }}
          SECRET_XPRA_WIN_8130: ${{ secrets.XPRA_WIN_8130 }}
        shell: julia --color=yes {0}
        run: |
          import Pkg
          Pkg.add(Pkg.PackageSpec(; name="MathOptInterface", rev=ENV["BRANCH"]))
          Pkg.develop("Xpress")
          Pkg.test("Xpress")
  test_cplex:
    name: CPLEX
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1'
      - name: Test CPLEX
        env:
          # To test on a PR, make a PR to update this environment variable.
          BRANCH: 'master'
          CPLEX_VERSION: '2010'
          SECRET_CPLEX_URL_12100: ${{ secrets.SECRET_CPLEX_URL_12100 }}
          SECRET_CPLEX_URL_2010: ${{ secrets.SECRET_CPLEX_URL_2010 }}
        shell: julia --color=yes {0}
        run: |
          import Pkg
          Pkg.add(Pkg.PackageSpec(; name="MathOptInterface", rev=ENV["BRANCH"]))
          Pkg.develop("CPLEX")
          Pkg.test("CPLEX")
